updated

diff --git a/01-toolchain b/01-toolchain
--- a/01-toolchain
+++ b/01-toolchain
@@ -1,4 +1,36 @@
-#!/bin/bash -e
+#!/bin/sh -e
+
+fetch() {
+	for s in $source; do
+		filename=${s##*/}
+		if [ "$s" != "$filename" ]; then
+			if [ ! -f $SRCDIR/$filename ]; then
+				echo "fetching $s"
+				curl -C - -L --fail --ftp-pasv --retry 999 --retry-delay 3 -o $SRCDIR/$filename.part $s && \
+					mv $SRCDIR/$filename.part $SRCDIR/$filename || {
+						echo "failed fetch $s"
+						exit 1
+					}
+			fi
+		fi
+	done
+}
+
+unpack() {
+	rm -fr "$WORKDIR/$pkg"
+	mkdir -p "$WORKDIR/$pkg"
+	for src in $source; do
+		filename=${src##*/}
+		case $src in
+			*.tar|*.tar.gz|*.tar.Z|*.tgz|*.tar.bz2|*.tbz2|*.tar.xz|*.txz|*.tar.lzma|*.zip)
+				echo "extracting $filename..."
+				tar -xf "$SRCDIR/$filename" -C "$WORKDIR/$pkg" || {
+					echo "failed extracting $filename"
+					exit 1
+				};;
+		esac
+	done
+}
 
 if type -p "sudo" &>/dev/null; then
     PRIV="sudo"
@@ -9,7 +41,7 @@ else
     exit 1
 fi
 
-fetch() {	
+fetch2() {	
 	tarballname=$(echo $1 | rev | cut -d / -f 1 | rev)
 	WGETCMD="wget --passive-ftp --tries=3 --waitretry=3 --output-document=$2/$tarballname.partial"
 	WGETRESUME="-c"
@@ -36,7 +68,7 @@ fetch() {
 	fi	
 }
 
-fetch_src() {
+fetch_src2() {
 	if [ "${#source[@]}" -gt 0 ]; then
 		for s in ${source[@]}; do
 			fetch $s $SRCDIR
@@ -44,7 +76,7 @@ fetch_src() {
 	fi
 }	
 
-extract_src() {
+extract_src2() {
 	[ "$name" ] && rm -fr $WORKDIR/$name
 	mkdir -p $WORKDIR/$name
 	if [ "${#source[@]}" -gt 0 ]; then
@@ -60,7 +92,7 @@ extract_src() {
 	fi
 }
 
-build_src() {
+buildtc() {
 	cd $WORKDIR/$name
 	if [ "$(type -t build)" = function ]; then
 		(set -e -x; build)
@@ -72,10 +104,6 @@ build_src() {
 		echo "--- build $name-$version success ---"
 	fi
 	[ "$name" ] && rm -fr $WORKDIR/$name
-	register
-}
-
-register() {
 	echo $name-$version > $LFS/tools/$(basename $script)
 }
 
@@ -89,21 +117,18 @@ checkdone() {
 	fi
 }
 
-build_stage1() {
-	cd $CWD
-	source $1 || exit 1
-	fetch_src
-	extract_src
-	build_src
-	unset source name version build
-}	
-
 main() {
 	for script in $TCDIR/[0-9][0-9]-*; do
 		checkdone || continue
-		build_stage1 $script
+		cd $CWD
+		. $script
+		pkg=$name
+		fetch
+		unpack
+		buildtc
+		unset source name version build
+		#build_stage1 $script
 	done
-	$PRIV chown -Rv 0:0 $LFS
 }
 
 if [ $(id -u) = 0 ]; then
@@ -127,10 +152,10 @@ LFS_TGT=x86_64-lfs-linux-gnu
 LFS_TGT32=i686-lfs-linux-gnu
 
 MAKEFLAGS="${MAKEFLAGS:--j$(nproc)}"
-LFS="${LFS:-/mnt/lfs}"
+LFS="${LFS:-$CWD/lfs-rootfs}"
 PKGDIR="${PKGDIR:-$CWD/pkg}"
 SRCDIR="${SRCDIR:-$CWD/src}"
-WORKDIR="${WORKDIR:-/tmp}"
+WORKDIR="${WORKDIR:-$CWD/work}"
 CFLAGS="${CFLAGS:--O2 -march=x86-64 -pipe}"
 
 export LC_ALL=C PATH MAKEFLAGS LFS LFS_TGT LFS_TGT32
@@ -138,15 +163,18 @@ export LC_ALL=C PATH MAKEFLAGS LFS LFS_TGT LFS_TGT32
 mkdir -p $SRCDIR $PKGDIR $WORKDIR
 
 if [ ! -d $LFS/tools ]; then
-	$PRIV mkdir -pv $LFS/tools
+	mkdir -pv $LFS/tools
 fi
 
 if [ ! -w $LFS ]; then
-	$PRIV chown -Rv $USER:$USER $LFS
+	echo "'$LFS' directory has no right access"
+	echo "please run 'chown -Rv $USER:$USER $LFS' as root"
+	exit 1
 fi
 
 if [ ! -L /tools ] || [ $(realpath /tools) != $LFS/tools ]; then
-	$PRIV ln -svf $LFS/tools /
+	echo "please create required '/tools' symlink by running 'ln -svf \$PWD/$LFS/tools' as root"
+	exit 1
 fi
 
 main $@
diff --git a/03-mkiso b/03-mkiso
--- a/03-mkiso
+++ b/03-mkiso
@@ -37,7 +37,7 @@ interrupted() {
 }
 
 cleanup() {
-	rm -fr $WDIR
+	rm -fr $ISODIR
 }
 
 die() {
@@ -55,39 +55,43 @@ printerror() {
 	echo -e "\e[0;31mERROR:\e[0m $*"
 }
 
+if [ $(id -u) != 0 ]; then
+	echo "$0 script need to run as root!"
+	exit 1
+fi
+
 CWD=$PWD
 
 if [ -f $CWD/config ]; then
 	source $CWD/config
 fi
 
-WDIR="$WORKDIR/iso"
+ISODIR="$CWD/iso"
 LABEL="LFSLIVECD"
 OUTPUT="lfs-livecd-$(date +"%Y%m%d").iso"
 FILEDIR="$CWD/files"
 
-MAKEFLAGS="${MAKEFLAGS:--j$(nproc)}"
-LFS="${LFS:-/mnt/lfs}"
+LFS="${LFS:-$CWD/lfs-rootfs}"
 PKGDIR="${PKGDIR:-$CWD/pkg}"
 SRCDIR="${SRCDIR:-$CWD/src}"
-WORKDIR="${WORKDIR:-/tmp}"
+WORKDIR="${WORKDIR:-$CWD/work}"
 
 isolinux_files="chain.c32 isolinux.bin ldlinux.c32 libutil.c32 reboot.c32 menu.c32 libcom32.c32 poweroff.c32"
 
-rm -fr $WDIR
-mkdir -p $WDIR
+rm -fr $ISODIR
+mkdir -p $ISODIR
 
 printstep "Preparing isolinux files..."
-mkdir -p $WDIR/{lfs,isolinux,boot}
+mkdir -p $ISODIR/{lfs,isolinux,boot}
 for file in $isolinux_files; do
-	cp $LFS/usr/share/syslinux/$file $WDIR/isolinux || die "failed copying '$file'"
+	cp $LFS/usr/share/syslinux/$file $ISODIR/isolinux || die "failed copying '$file'"
 done
-#cp isolinux/splash.png $WDIR/isolinux
-cp $FILEDIR/isolinux.cfg $WDIR/isolinux
-[ -d rootfs ] && cp -Ra rootfs $WDIR
+#cp isolinux/splash.png $ISODIR/isolinux
+cp $FILEDIR/isolinux.cfg $ISODIR/isolinux
+[ -d rootfs ] && cp -Ra rootfs $ISODIR
 
 printstep "Make squash filesystem..."
-mksquashfs $LFS $WDIR/lfs/root.sfs \
+mksquashfs $LFS $ISODIR/lfs/root.sfs \
 		-b 1048576 -comp xz -Xdict-size 100% \
 		-e $LFS/var/lib/pkg/src/* \
 		-e $LFS/var/lib/pkg/pkg/* \
@@ -96,34 +100,34 @@ mksquashfs $LFS $WDIR/lfs/root.sfs \
 		-e $LFS/tmp/* 2>/dev/null || die "failed create squashed filesystem"
 
 printstep "Preparing kernel and initramfs..."
-cp $LFS/boot/vmlinuz-lfs $WDIR/boot/vmlinuz || die "failed copying kernel"
+cp $LFS/boot/vmlinuz-lfs $ISODIR/boot/vmlinuz || die "failed copying kernel"
 cp files/livecd.hook $LFS/etc/mkinitramfs.d
 kernver=$(file $LFS/boot/vmlinuz-lfs | cut -d ' ' -f9)
 chroot_run mkinitramfs -k $kernver -a livecd -o /boot/initrd-live.img || die "failed create initramfs"
-mv $LFS/boot/initrd-live.img $WDIR/boot/initrd || die "failed copying initrd"
+mv $LFS/boot/initrd-live.img $ISODIR/boot/initrd || die "failed copying initrd"
 
 printstep "Setup UEFI mode..."
-mkdir -p $WDIR/boot/{grub/{fonts,x86_64-efi},EFI}
+mkdir -p $ISODIR/boot/{grub/{fonts,x86_64-efi},EFI}
 if [ -f $LFS/usr/share/grub/unicode.pf2 ];then
-	cp $LFS/usr/share/grub/unicode.pf2 $WDIR/boot/grub/fonts
+	cp $LFS/usr/share/grub/unicode.pf2 $ISODIR/boot/grub/fonts
 fi
-if [ -f $WDIR/isolinux/splash.png ]; then
-	cp $WDIR/isolinux/splash.png $WDIR/boot/grub/
+if [ -f $ISODIR/isolinux/splash.png ]; then
+	cp $ISODIR/isolinux/splash.png $ISODIR/boot/grub/
 fi
-echo "set prefix=/boot/grub" > $WDIR/boot/grub-early.cfg
-cp -a $LFS/usr/lib/grub/x86_64-efi/*.{mod,lst} $WDIR/boot/grub/x86_64-efi || die "Failed copying efi files"
-cp $FILEDIR/grub.cfg $WDIR/boot/grub/
+echo "set prefix=/boot/grub" > $ISODIR/boot/grub-early.cfg
+cp -a $LFS/usr/lib/grub/x86_64-efi/*.{mod,lst} $ISODIR/boot/grub/x86_64-efi || die "Failed copying efi files"
+cp $FILEDIR/grub.cfg $ISODIR/boot/grub/
 
-grub-mkimage -c $WDIR/boot/grub-early.cfg -o $WDIR/boot/EFI/bootx64.efi -O x86_64-efi -p "" iso9660 normal search search_fs_file
+grub-mkimage -c $ISODIR/boot/grub-early.cfg -o $ISODIR/boot/EFI/bootx64.efi -O x86_64-efi -p "" iso9660 normal search search_fs_file
 modprobe loop
-dd if=/dev/zero of=$WDIR/boot/efiboot.img count=4096
-mkdosfs -n LFSLIVECD-UEFI $WDIR/boot/efiboot.img || die "Failed mkdosfs"
-mkdir -p $WDIR/boot/efiboot
-mount -o loop $WDIR/boot/efiboot.img $WDIR/boot/efiboot || die "Failed mount efiboot.img"
-mkdir -p $WDIR/boot/efiboot/EFI/boot
-cp $WDIR/boot/EFI/bootx64.efi $WDIR/boot/efiboot/EFI/boot
-umount $WDIR/boot/efiboot
-rm -fr $WDIR/boot/efiboot
+dd if=/dev/zero of=$ISODIR/boot/efiboot.img count=4096
+mkdosfs -n LFS-UEFI $ISODIR/boot/efiboot.img || die "Failed mkdosfs"
+mkdir -p $ISODIR/boot/efiboot
+mount -o loop $ISODIR/boot/efiboot.img $ISODIR/boot/efiboot || die "Failed mount efiboot.img"
+mkdir -p $ISODIR/boot/efiboot/EFI/boot
+cp $ISODIR/boot/EFI/bootx64.efi $ISODIR/boot/efiboot/EFI/boot
+umount $ISODIR/boot/efiboot
+rm -fr $ISODIR/boot/efiboot
 
 printstep "Making the iso..."
 rm -f $OUTPUT
@@ -139,7 +143,7 @@ xorriso -as mkisofs \
     -no-emul-boot \
     -isohybrid-gpt-basdat \
     -volid $LABEL \
-    -o $OUTPUT $WDIR || die "failed create iso"
+    -o $OUTPUT $ISODIR || die "failed create iso"
 
 printstep "Cleaning up..."
 cleanup
