updated

diff --git a/01-toolchain b/01-toolchain
--- a/01-toolchain
+++ b/01-toolchain
@@ -32,71 +32,9 @@ unpack() {
 	done
 }
 
-if type -p "sudo" &>/dev/null; then
-    PRIV="sudo"
-elif type -p "doas" &>/dev/null; then
-    PRIV="doas"
-else
-    echo -e "\e[1;31merror:\e[0m sudo/doas not found!"
-    exit 1
-fi
-
-fetch2() {	
-	tarballname=$(echo $1 | rev | cut -d / -f 1 | rev)
-	WGETCMD="wget --passive-ftp --tries=3 --waitretry=3 --output-document=$2/$tarballname.partial"
-	WGETRESUME="-c"
-	
-	if [ -f $2/$tarballname ]; then
-		echo "Source file $tarballname found."
-		return 0
-	else
-		if [ -f $2/$tarballname.partial ]; then
-			echo "Resuming $1"
-			$WGETCMD $WGETRESUME $1
-		else
-			mkdir -p "$2"
-			echo "Downloading $1"
-			$WGETCMD $1
-		fi
-	fi
-	
-	if [ $? = 0 ]; then
-		mv $2/$tarballname.partial $2/$tarballname
-	else
-		echo "Failed fetching source: $tarballname"
-		exit 1
-	fi	
-}
-
-fetch_src2() {
-	if [ "${#source[@]}" -gt 0 ]; then
-		for s in ${source[@]}; do
-			fetch $s $SRCDIR
-		done
-	fi
-}	
-
-extract_src2() {
-	[ "$name" ] && rm -fr $WORKDIR/$name
-	mkdir -p $WORKDIR/$name
-	if [ "${#source[@]}" -gt 0 ]; then
-		for s in ${source[@]}; do
-			filename=$(basename $s)
-			case $filename in
-				*.tar|*.tar.gz|*.tar.Z|*.tgz|*.tar.bz2|*.tbz2|*.tar.xz|*.txz|*.tar.lzma|*.zip|*.rpm)
-					tar xvf $SRCDIR/$filename -C $WORKDIR/$name || exit 1;;
-				*)
-					cp -v $SRCDIR/$filename $WORKDIR/$name || exit 1;;
-			esac
-		done
-	fi
-}
-
 buildtc() {
 	cd $WORKDIR/$name
-	if [ "$(type -t build)" = function ]; then
-		(set -e -x; build)
-	fi
+	(set -e -x; build)
 	if [ $? -ne 0 ]; then
 		echo "!!! build $name-$version failed !!!"
 		exit 1
@@ -115,6 +53,10 @@ checkdone() {
 		echo ">>> building $(basename $script) <<<"
 		return 0
 	fi
+}
+
+build() {
+	:
 }
 
 main() {
@@ -168,12 +110,12 @@ fi
 
 if [ ! -w $LFS ]; then
 	echo "'$LFS' directory has no right access"
-	echo "please run 'chown -Rv $USER:$USER $LFS' as root"
+	echo "Please run 'chown -Rv $USER:$USER $LFS' as root"
 	exit 1
 fi
 
 if [ ! -L /tools ] || [ $(realpath /tools) != $LFS/tools ]; then
-	echo "please create required '/tools' symlink by running 'ln -svf \$PWD/$LFS/tools' as root"
+	echo "Please create required '/tools' symlink by running 'ln -svf $LFS/tools /tools' as root"
 	exit 1
 fi
 
diff --git a/02-base b/02-base
--- a/02-base
+++ b/02-base
@@ -1,18 +1,16 @@
 #!/bin/sh
 
 lfs_dirs() {
-	#mkdir -pv $LFS/dev
-	#mknod -m 600 $LFS/dev/console c 5 1 || true
-	#mknod -m 666 $LFS/dev/null c 1 3 || true
-
-	mkdir -pv $LFS/bin $LFS/usr/{lib,bin} $LFS/etc || true
-	ln -svf /tools/bin/{bash,cat,chmod,dd,echo,ln,mkdir,pwd,rm,stty,touch} $LFS/bin
-	ln -svf /tools/bin/{env,install,perl,printf}         $LFS/usr/bin
-	ln -svf /tools/lib/libgcc_s.so{,.1}                  $LFS/usr/lib
-	ln -svf /tools/lib/libstdc++.{a,so{,.6}}             $LFS/usr/lib
-
+	mkdir -pv $LFS/bin $LFS/usr/lib $LFS/usr/bin $LFS/etc || true
+	for i in bash cat chmod dd echo ln mkdir pwd rm stty touch; do
+		ln -svf /tools/bin/$i $LFS/bin
+	done
+	for i in env install perl printf; do
+		ln -svf /tools/bin/$i $LFS/usr/bin
+	done
+	ln -svf /tools/lib/libgcc_s.so /tools/lib/libgcc_s.so.1 $LFS/usr/lib
+	ln -svf /tools/lib/libstdc++.a /tools/lib/libstdc++.so /tools/lib/libstdc++.so.6 $LFS/usr/lib
 	ln -svf bash $LFS/bin/sh
-
 	ln -svf /proc/self/mounts $LFS/etc/mtab
 
 cat > $LFS/etc/passwd << "EOF"
@@ -47,12 +45,15 @@ users:x:999:
 EOF
 
 	# pkgutils
-	mkdir -p $LFS/var/lib/pkg/{pkg,src,work}
+	mkdir -p \
+		$LFS/var/lib/pkg/pkg \
+		$LFS/var/lib/pkg/src \
+		$LFS/var/lib/pkg/work
 	touch $LFS/var/lib/pkg/db
 }
 
 mount_pseudo() {
-	mkdir -p $LFS/{dev,run,proc,sys}
+	mkdir -p $LFS/dev $LFS/run $LFS/proc $LFS/sys
 	mount --bind /dev $LFS/dev
 	mount -t devpts devpts $LFS/dev/pts -o gid=5,mode=620
 	mount -t proc proc $LFS/proc
@@ -89,7 +90,7 @@ unmount() {
 }
 
 runinchroot() {
-	pushd $LFS &>/dev/null
+	cd $LFS >/dev/null 2>&1
 	mount_pseudo
 	mountbind_srcpkg
 	cp -L /etc/resolv.conf $LFS/etc/
@@ -101,7 +102,7 @@ runinchroot() {
 	retval=$?
 	unmountbind_srcpkg
 	umount_pseudo
-	popd &>/dev/null
+	cd - >/dev/null 2>&1
 	return $retval
 }
 
@@ -117,10 +118,10 @@ die() {
 }
 
 printerror() {
-	echo -e "ERROR: $@"
+	echo "ERROR: $@"
 }
 
-trap "interrupted" SIGHUP SIGINT SIGQUIT SIGTERM
+trap "interrupted" 1 2 3 15
 
 if [ $(id -u) != 0 ]; then
 	echo "$0 script need to run as root!"
@@ -130,7 +131,7 @@ fi
 CWD=$PWD
 
 if [ -f $CWD/config ]; then
-	source $CWD/config
+	. $CWD/config
 fi
 
 MAKEFLAGS="${MAKEFLAGS:--j$(nproc)}"
@@ -140,6 +141,8 @@ SRCDIR="${SRCDIR:-$CWD/src}"
 WORKDIR="${WORKDIR:-$CWD/work}"
 CFLAGS="${CFLAGS:--O2 -march=x86-64 -pipe}"
 
+mkdir -p $PKGDIR $SRCDIR $WORKDIR
+
 if [ -x $LFS/usr/bin/env ]; then
 	ENVLFS=/usr/bin/env
 else
@@ -147,7 +150,7 @@ else
 fi
 
 PKGS="filesystem linux-api-headers man-pages glibc tzdata zlib bzip2 file readline m4 bc binutils gmp mpfr mpc attr acl shadow gcc
-	pkg-config ncurses libcap sed psmisc iana-etc bison flex grep bash libtool gdbm gperf expat inetutils
+	pkgconf ncurses libcap sed psmisc iana-etc bison flex grep bash libtool gdbm gperf expat inetutils
 	perl perl-xml-parser intltool autoconf automake xz kmod gettext elfutils libffi openssl python3 coreutils
 	diffutils gawk findutils groff fuse2 grub less gzip iproute2 kbd libpipeline make patch man-db tar texinfo vim procps-ng
 	util-linux e2fsprogs sysklogd sysvinit eudev lfs-bootscripts linux-firmware libarchive mkinitramfs linux libtasn1 p11-kit ca-certificates 
